### ISSUE TITLE
Implement deep sleep between readings

### ISSUE THREAD

**Issue by amotl** [hiveeyes/hiveeyes-micropython-firmware#2]
People have been asking [1,2] for Deep Sleep on FiPy. While @einsiedlerkrebs and others [3] tried already,

> I have tried deep sleep, but without success. Tried 1s sleep but device didn't wake up.
> 
> I have to admit that I did not do any debugging on this yet.
> see: [hiveeyes/hiveeyes-micropython-firmware@191a46b](https://github.com/hiveeyes/hiveeyes-micropython-firmware/commit/191a46b9a6063ce2d05997e655a3f9e5164bd683)

it looks like it would be harder than expected. As usual, the devil might just be in the details.

We will try to dedicate some time to that exceptionally important detail.

[1] https://community.hiveeyes.org/t/bob-platine-im-lipo-betrieb-ohne-deep-sleep/2055
[2] https://github.com/Hiverize/FiPy/issues/2
[3] https://github.com/pycom/pycom-libraries/issues/26

**Comment by amotl** [comment]
Please recognize there's also the Deep Sleep Shield [1-4]. However, while Pycom and Espressif might have had their times [5-7], the devices might now be ready [8] to eventually feature the promised ultra low power operation (~1uA in deep sleep) [9], even when using only the RTC module for implementing Deep Sleep.

[1] https://docs.pycom.io/datasheets/boards/deepsleep/
[2] https://docs.pycom.io/.gitbook/assets/deepsleep-schematic.pdf
[3] https://media.digikey.com/pdf/Data%20Sheets/Pycom%20PDFs/Deep_Sleep_Shield_Web.pdf
[4] https://forum.pycom.io/topic/3977/power-supply-issue-by-vin-on-sipy-deep-sleep-shield

[5] https://forum.pycom.io/topic/543/lopy-deep-sleep-mode
[6] https://forum.pycom.io/topic/1022/root-causes-of-high-deep-sleep-current-lopy1-wipy2-and-sipy-all-the-new-modules-do-not-have-deepsleep-issues
[7] https://forum.pycom.io/topic/989/pycom-oem-modules-are-here-4-mbytes-of-ram-and-deep-sleep-test
[8] https://pycom.io/l01-oem-module-deep-sleep-test/
[9] https://www.kickstarter.com/projects/pycom/fipy-the-worlds-first-5-network-iot-dev-board

**Comment by amotl** [comment]
> Please recognize there's also the Deep Sleep Shield.

After some quick research, it appears to us that the [Deep Sleep API] is solely suitable for talking to the [Deep Sleep Shield]. On the other hand, another part of the documentation just called [Sleep] tells us that the respective routines for controlling sleep mode there would be *embedded into the Pytrack and Pysense libraries*.

So, as the native MicroPython's [machine.deepsleep] will probably not be available on the ESP32-based Pycom platform, we should nevertheless bring in the use of [pycoproc.py] in order to see what we can get from that running on a bare FiPy module without any of the Deep Sleep Shield or Pysense or Pytrack extension boards.

[Deep Sleep API]: https://docs.pycom.io/datasheets/boards/deepsleep/api.html
[Deep Sleep Shield]: https://docs.pycom.io/datasheets/boards/deepsleep/
[Sleep]: https://docs.pycom.io/pytrackpysense/apireference/sleep.html
[machine.deepsleep]: https://docs.micropython.org/en/latest/library/machine.html#machine.deepsleep
[pycoproc.py]: https://github.com/pycom/pycom-libraries/blob/master/lib/pycoproc/pycoproc.py

**Comment by amotl** [comment]
> as the native MicroPython's machine.deepsleep will probably not be available on the ESP32-based Pycom platform

However, they actually **are** using `machine.deepsleep()` in this video.

![image](https://user-images.githubusercontent.com/453543/59094311-2421ee00-8916-11e9-8082-424f28cdf051.png)

**Comment by ClemensGruber** [comment]
The PyCom deep sleep shield is only necessary for older WiPy / LoPy devices! It was necessary due to a hardware bug and was a workaround to get this older boards in a power saving operation mode! 

It is NOT necessary for the current WiPy, LoPy or FiPy version!! See https://forum.pycom.io/topic/1022/root-causes-of-high-deep-sleep-current-lopy1-wipy2-and-sipy-all-the-new-modules-do-not-have-deepsleep-issues/88

**Comment by ClemensGruber** [comment]
Ok, the "DeepSleep library" is for the deep sleep shield only as @amotl mentioned! I found [this remark ](https://github.com/pycom/pycom-libraries/issues/26) for the new boards:

> The WiPy3 has its own deep sleep functionality, which is part of the machine module https://docs.pycom.io/chapter/firmwareapi/pycom/machine/

Link is outdated, current is https://docs.pycom.io/firmwareapi/pycom/machine/ and here you can find

> 
> machine.deepsleep([time_ms])
> 
> Stops the CPU and all peripherals, including the networking interfaces (except for LTE). Execution is resumed from the main script, just as with a reset. If a value in milliseconds is given then the device will wake up after that period of time, otherwise it will remain in deep sleep until the reset button is pressed.
> 
> The products with LTE connectivity (FiPy, GPy, G01), require the LTE radio to be disabled separately via the LTE class before entering deepsleep. This is required due to the LTE radio being powered independently and allowing use cases which require the system to be taken out from deepsleep by an event from the LTE network (data or SMS received for instance).

**Comment by amotl** [comment]
It looks like this guy is sleeping well and even wakes up again.
```
4.7042 [terkin.datalogger        ] INFO   : Reset cause and wakeup reason: {'reset_cause': {'code': 3, 'message': 'DEEPSLEEP'}, 'wakeup_reason': {'code': 2, 'message': 'RTC'}}
```

We will be happy to find any testers out there. Thanks already, @ClemensGruber! ;]

**Comment by amotl** [comment]
@ClemensGruber confirmed this would also work for him, thanks for testing! So we are closing this but feel free to reopen.

**Comment by einsiedlerkrebs** [comment]
Yip, looks good! 

Am 7. Juni 2019 21:30:20 MESZ schrieb Andreas Motl <notifications@github.com>:
>It looks like this guy is sleeping well and even wakes up again.
>```
>4.7042 [terkin.datalogger        ] INFO   : Reset cause and wakeup
>reason: {'reset_cause': {'code': 3, 'message': 'DEEPSLEEP'},
>'wakeup_reason': {'code': 2, 'message': 'RTC'}}
>```
>
>We will be happy to find any testers out there. Thanks already,
>@ClemensGruber! ;]


-- 
encryption? welcome!

gpg: 63e5d348

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFiDKSkBEACjAoZDjZ2GyPrW919ozieezixTX9+k9meyyDOxS+koA3YCdUMk
L7+xwvPgCc/ZY6Ug3EF6+wJxVd+xZcAAGc4Lo8b9Fdrrg/YNbqjitIMA4gatBnEJ
gDO4qrYmwGzA214yINLpSR+Pv6mMv4Y628FltkOnFrVDND3DnqOTLzq8tQHskaLQ
KHgUYNUq93yVjSvquaJgpaJJQbGYyhSehvNLqPRdgC6rvJqAxh4InsclfaGWybxz
cDPDLdUQEefg/kyeY0+IfYGQZgbr0jNRGZLbwFUSaCDpJlIAb3IABUUPj/HKwlP6
UDWyNTbXMdSedXaeRHpdUki33gbD8Q8CqVB5sDyR2nZiXGBuM9v6drQRCRrGalm+
eFTLWPajM53kCLnnNDYv4upiS+2jqKHtQ/txyVqIDkNme5zCzxs63O8OJA57Go53
r4ULfSU0pUDo8c8K58JBXLeovIsXUkdC+KlBXVMNEd/HxUhGIsTyZcs2a/j/2mrr
gkzE2wAY2H5Q0rjMp0OCjomYUgG0/fNL5JZP11m3N84Au7H6qGwXoQbSe9YwK3S3
hZW64Grr6Twi5cB3+fe8QaWuwZt8lHbyySF9CSsTSI2wtAcmllNv4+BYu3foF9Z2
YlZJ8nPZkuajkhMnLIabaps3bsPhSlxD17/PizDOE0WM7GxazoJfNCUBIQARAQAB
tCRteCBtc3RybW5uIDxyaWNoYXJkQGdpbm51bmdhZ2FwLm9yZz6JAk4EEwEIADgW
IQRYiB2ee4h0BkApXNhM0u7DY+XTSAUCWIMpKQIbAwULCQgHAgYVCAkKCwIEFgID
AQIeAQIXgAAKCRBM0u7DY+XTSMJeEACYk6slxE1ktg1fR2Nrv/NU6zvPWUS28BVX
FplxYFTNEKZIS7I2ztL6BRnxtqoJoiMhTbzSINGW7lMk13r8D7r/VjtorcDVY6Fa
Tmn2b1SemmQVnlAaW1rQr1Zf+kyuShROrUbQMMibhV/Im5f6fkciFIjlgX4Ejyo0
ItuvOQUGXBfjXk78Q0j856u888PMj0QGOaiR1lZGu3Vv/Z0+JmwlYDIsVo7H4hPO
Nj+x0HWktjAMfoewMUbDi27k0UWU3pYDFcJ/xxgZQKVlk4iL7RpskSk9VvcW9Vns
MngEHDeovUxzx4/hz4B+O54CUmgYOBVhPoI+lBzKOejbeyGbb6qxOSjPoffjdhzo
hCYaxbIHSthzZ1o848mFYLaNnirYrbyWjGXNzBcuqdvXCic8nKAH9zNoImDEKsGF
Nem8iaClcL9vKVELRJ8VEffnTuooa3UPYBZfx53IyDvyrlKDQRH8pVEbr8ce3InB
XbNT19M8QiKggA+vI7h0YcBGMguhBQqSocGNzxE+EuX+xgsacR2GsrqwknhFLCHA
zZZEzxa7QsJtb1Meyo6JnXm0RvzKXYueGn4CM1LqGyXB25imf4TuDu6quZ7sDWu1
qLJ/I2qzXAC+ayDmJoNi52T1Oarw+HxtIFbQC8SrA9ArUfsZOBho6JahvdXPbFel
JZEDcWqyTrQvZWluc2llZGxlcmticyA8ZWluc2llZGxlcmtyZWJzQGdpbm51bmdh
Z2FwLm9yZz6JAk4EEwEIADgWIQRYiB2ee4h0BkApXNhM0u7DY+XTSAUCWIMqgwIb
AwULCQgHAgYVCAkKCwIEFgIDAQIeAQIXgAAKCRBM0u7DY+XTSDibEACJWr5TWA4u
6jlv6G1w4RZh7GR/rebd8D6/SpwAnyLRgYoicMRWMp/1QPSXMzTvLPk6SqmqwBSE
avD7v6FmjAuUwhWCPVSPE38qU3BjxMsZaEMLhSPQRuL0HFGO9WUE2rGSlQyuXMPF
inGAnaHgDoxtG0mtsVWvm3kgZ7bn1lQxwncfPu4fr8kXJSLXM3vhZrqwpze/F0Q5
q8YpVeLZPiK7LzxIDmiEt9FY7Z5ZIu3GCDu/uR8+GEDlnD2AoL7JnOK9ECxEXpUy
9cvr8ubOpocrshrqpIYWZLF1A+8KCUrMfTgPOCe5a8djrZGpelrlyVQkoW2W6L/3
D7Yj5j4H1c32J+OBc/VjASKHIwsIjaeyqttKtcv4TD3513YworWrSZskEQWzgtAK
6Rhr9FHMpw5ySxNgEMpIfwDyz8WrY5ymamDRVB1ZP898xJ2KlCd2HnN7NgKCylGO
jQiUN3je8PiSk6qERCw62lS/hFyxXDypVNMzHYenWyJm9vdd1md0VZGxM12UONeQ
DhkYF6sjOcN9D/2NOdQ2ySi664dBUlC+MfOOM5DTAxAYDyf6/eDMkZ470+ko5J2G
iG7Oj5mcHaAJH9pz+/SDCDf2XZzIIKKASOolpjKtP5QbICkK6cvZxZ5fxqKBQPka
neeol2r+5q7Nsn3Bsk0tq0tGzK7eDN0Qh7kCDQRYgykpARAA1hiPo3fYTLXMv8te
UJkyDXQjr+czb59yvHXWeRMjcp3PkgLCOPzI1Hj4ESYT6uCrcaiAy3bw4TUpHHKE
05+s/a9T23/OR46+gzkDbC0zHPGqvSY2vMMQpbgo5MAwOQLBvn65q5gH+yI9M6ZN
MHMHondUr8Xdsbv/CALMEDSNam3pgssLAL09Mo0b/vyC+uIDJxXNePOboYFGoZbH
VUrL1cmaW0OLVQbiyTK/dBZFPmY0ertSue7UqvyrCSgYCVnCEiF6fYpUFS9jeKO2
bP7Q23Kjie+IfeDP4GWJI8AqaEwOL1B3n5OqUA4vQrH4pIPnJXPkDE2j3969xiq5
d5tbjy1XrgyXE9vICJ8OghtIZPEf1z6j+N/296jnjFt/xfUZr57Y5VX3mLERbINH
pE25HF3RVY3wx8QfTjR4akHHK0JPiu/u8EiDcRL8HhC0ow5MMTQclG5I8OxrQi/R
7T06VeXonncYHFWqLClbasuL8cqGwaORVs2q+5wXIVQcEEcP5EkIJNfckVL9ihyy
uQj/q8+t+saGUVO8xPfnM/Aqn+XSnZbwkNk9TozEgGHl0gSP/WjRaWxHxeBEfGJ3
PoQDpyUYFFt/Y3zCicO+Seo9OD1pYkB2fQzyDxbwvcZr39kXboXNpP68qrLgcarg
aWMXcl0hpRUFzb9Ws1DnRCZmkUEAEQEAAYkCNgQYAQgAIBYhBFiIHZ57iHQGQClc
2EzS7sNj5dNIBQJYgykpAhsMAAoJEEzS7sNj5dNIGeMQAJOCa6hgeEUdZX+2eAYQ
SE/RHnXESekjiZAizu83FZ+m1UdKzBXERnB/SC9pBMhmM3QnQg1Ni/tWLSVA83gN
6osw5/gmLciYzQawcC91iWyksoPbsUeecku4S5GfDsSpJexXbn0oabWGBf7L73yh
shJ2DpbRohjZf/gTn1d7gyrB3h7WJIlCEbM/aHPe5a2hr8HDdm/YSxyyJI8ZN4mt
JbQ7pFXF29N9BtrCj7pOcog2rC72x68v1YJw7EVBhq+CeLZ/suRnVKhX17hlKgA3
uQFxPGfQtUlVNdwmgkTWJ8FaZzbXzpZPxa+0TnOQJpCLqWgFFYaaGytrQGuAmhvY
asSvunxkoq/nhu5rphSkJKuWYfMDE8Ux7rvpupkzSfGAraxNxBFVLQ8AYll81iD/
O7JNcHqupBFq7taPjLU6UwXYmQWptNx2pel6kokPhsV2TezM/oO5nMkgMot6hoaH
gZ7mw+0tWuWXcQW+GtWzMX7y/5vELleUOrUYsV76KJ3yY+u7LRm5nw0gH3Jjc1e0
TDQNviaUI6bbWPA2+bQhQMva3r7SyQH2BNdoijAMC+pQdJJseEHkLIrVDpaxQ+mH
cC2R3J27GAXJDagPilUARrOxD71gnFxJGiKAEvbtLORoxMsLl3uhosG3vyDL5nxy
+cbOghoUEZPyzUyfOFxMG3hy
=81oF
-----END PGP PUBLIC KEY BLOCK-----

**Comment by amotl** [comment]
@ClemensGruber told us at [1] that

> I believe deep sleep still does not work as intended. When configuring
```
'interval' 60.0,
'deepsleep': True,
```
> it feels like the WiPy is only sleeping for 5 seconds.

[1] https://community.hiveeyes.org/t/sammelthread-kontinuierliches-bugfixing-der-hiveeyes-micropython-software/2115/3

---

Thanks for the report!

**Comment by amotl** [comment]
We still had a glitch in there but it should work now.

**Comment by ClemensGruber** [comment]
It's working now as a kind of delay after doing sensor reading and submitting. I had to do `make install` to get the fix running. `make sketch-and-run` is not sufficien only!

**Comment by amotl** [comment]
Dear @ClemensGruber,

this issue was really just about making `machine.deepsleep()` work at all ;]. Sorry that you are having problems updating your program. The documentation is gradually improving and we will be happy about appropriate contributions.

Also, we would like to tell you that we are tracking the appropriate computation of the delay as a real interval with #4.

With kind regards,
Andreas.
