### ISSUE TITLE
Running "make setup" inside Docker

### ISSUE THREAD

**Issue by amotl** [hiveeyes/hiveeyes-micropython-firmware#20]
Dear @poesel,

after merging your update from #19 to the `check-program` rule, `make setup` stopped working but croaked at us:
```bash
make setup
ERROR: "virtualenv" program not installed.
HINT: Install on Debian-based systems using 'apt install python-virtualenv python3-virtualenv' or use the package manager of your choice
make[1]: *** [check-program] Error 1
make: *** [check-virtualenv] Error 2
```

We reverted this amendment by 29804607. Please feel free to get back to us here in order to sort things out. Why that would not work on **your** machine is currently beyond my imagination. May I humbly ask on which environment you are running this?

With kind regards,
Andreas.

**Comment by poesel** [comment]
I ran this in the docker container created by docker-compose.yml on Win10 and MacOS.

I remember to have had this error when the Docker file didn't have 'python-virtualenv python3-virtualenv' in the apt-get line. The image was then missing virtualenv hence the error. 
Did you maybe still have the image from the 'old' Dockerfile?

**Comment by amotl** [comment]
Dear @poesel,

thanks for describing your environment and for adding the Docker support files to this repository.

For our part, we verified the behavior on a native macOS system using _GNU Make 3.81_ from _Homebrew_.
```bash
$ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

We believe support for running the build environment within a Docker container is a very valuable contribution, so we humbly ask you to give this another chance to a) reproduce the behavior and b) give us some more hints to be able to conclude the root cause of this problem.

Thanks and with kind regards,
Andreas.

**Comment by poesel** [comment]
This is what I did on a Win10 host. Before that I purged all docker images and the hiveeyes directory.
This is a start from a clean slate.

git clone https://github.com/poesel/hiveeyes-micropython-firmware.git
cd hiveeyes-micropython-firmware
git checkout fix-make-setup
docker-compose build
docker-compose up -docker-compose
Browser: http://localhost:9000/ -> connect to hiveyes image and open console
cd opt/hiveeyes-micropython-firmware/
make setup 

Done. Now there is a complete dev directory which is under git control from your own repository (which is a fork from hiveeyes of course).

The only irregularity I saw was this:
root@1a600b9173b1:/opt/hiveeyes-micropython-firmware# make setup
make[1]: Entering directory '/opt/hiveeyes-micropython-firmware'
make[1]: command: Command not found
make[1]: Leaving directory '/opt/hiveeyes-micropython-firmware'
but it ran through anyway.

Sorry, but I can't see a problem. I will repreat the process on MacOS later.

**Comment by poesel** [comment]
I ran it on MacOS, too. Same result.

**Comment by amotl** [comment]
Thanks for your investigations.

So, the last thing would be to mitigate this `command: Command not found` and then everything would be fine?

**Comment by poesel** [comment]
Yes. Although I haven't tested anything beyond 'make setup' because that is all I currently need.
Also I have to find out how to connect the docker container to USB for any interaction with the MCU.

**Comment by amotl** [comment]
`command: Command not found` probably comes from the `check-program` rule and we should well care about this.

https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/11f7a44a80c9852c7d5294ac9cf05b2d78666794/tools/core.mk#L136-L141

Do you see another way to check for the existence of a program on `PATH` in a platform-agnostic manner to make this work on Windows?

**Comment by amotl** [comment]
We will use `which` instead of `command` from now on. Let's see how that goes.
