### ISSUE TITLE
Add HX711 section in settings.example.py

### ISSUE THREAD

**Issue by ClemensGruber** [hiveeyes/hiveeyes-micropython-firmware#3]
There is no HX711 for the load cell specified in `settings.example.py`, we should add e.g. 

    'registry': {
        'hx711': {
            'pin_dout': 'P22',
            'pin_pdsck': 'P21',
            'scale': 11.026667,
            'offset': 130800.0,
        },

**Comment by amotl** [comment]
Thanks!
