### ISSUE TITLE
Review implementations of system sensors for Pycom MicroPython

### ISSUE THREAD

**Issue by amotl** [hiveeyes/hiveeyes-micropython-firmware#5]
We just completed reasonable implementations of the most important system sensors we have been aiming at. They acquire runtime metrics from the ESP32 MCU and the FreeRTOS system running the Pycom MicroPython firmware. In general, this is about system uptime, WiFi reception and last but not least package temperature, free memory and battery level.

Especially, we would like to thank @ayoy for the Pycom MicroPython implementation of `system.voltage` we have been able to reuse from [1].

You can find these sensor implementations called `SystemMemoryFree`, `SystemTemperature`,  `SystemUptime` and `SystemBatteryLevel` nicely wrapped up for reuse inside the [terkin.sensor.system](https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/master/terkin/sensor/system.py) module.

As a picture says a thousand words, here is an example telemetry payload message yielded from these sensors.
```
{
  "system.time": 921,
  "system.runtime": 16,
  "system.uptime": 4202.907,
  "system.temperature": 41.30435,
  "system.memfree": 2262960,
  "system.voltage": 4.322425,
  "system.wifi.bandwidth": 2,
  "system.wifi.channel": 3,
  "system.wifi.country": "DE",
  "system.wifi.max_tx_power": 78,
  "system.wifi.rssi": -56
}
```

[1] https://github.com/ayoy/upython-aq-monitor/blob/lora/lib/adc.py

**Comment by amotl** [comment]
As others also have been asking about reading the battery level [1], @vkuhlen, @Diren, @ClemensGruber or @pinguin999 might be interested as well. So thanks again, @ayoy!

[1] https://github.com/Hiverize/FiPy/issues/7

**Comment by amotl** [comment]
Dear Dominik (@ayoy),

we pinged you already to appreciate the implementation for reading the battery level you have provided through your air quality monitoring device [1]. As we are also currently conceiving an ESP32-based Pycom datalogger these days, our implementation might spark your interest.

As we are currently only running USB-powered [2], we would humbly like to ask if the readings and observations outlined below would actually make sense then?
```
18.1523 [terkin.sensor.system] DEBUG: Reading battery level
18.2500 [terkin.sensor.system] DEBUG: SystemBatteryLevel: Mean of ADC readings (0-4095) = 4095.0002670288086
18.2627 [terkin.sensor.system] DEBUG: SystemBatteryLevel: Mean of ADC voltage readings (0-1382mV) = 1381.9999694824219
18.2752 [terkin.sensor.system] DEBUG: SystemBatteryLevel: Variance of ADC readings = 0.0000000000000
18.2878 [terkin.sensor.system] DEBUG: SystemBatteryLevel: 10**6*Variance/(Mean**2) of ADC readings = 0.0000000000000
18.2985 [terkin.sensor.system] DEBUG: Finished reading battery level: 4
```

Thanks already and with kind regards,
Andreas.

[1] https://github.com/ayoy/upython-aq-monitor/tree/lora
[2] https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/master/README-HARDWARE.md#hiveeyes-buerger

**Comment by ClemensGruber** [comment]
Seems that battery monitoring is optimized for typical 4,2 V LiPos and a USB-Option or other battery optin up to 5 V is not possible with the used voltage divider (on the extension board?). 

On the v3 of the Pycom expansion board https://docs.pycom.io/datasheets/boards/expansion3.html is a 115 kΩ (R1) / 56 kΩ (R2) voltage divider used. It drops 5 V to 1.637 V, too much for FiPy's ADC (ADC pin input range is 0-1.1V). 

But there is also a remark https://docs.pycom.io/firmwareapi/pycom/machine/adc.html

>his maximum value can be increased up to 3.3V using the highest attenuation of 11dB. Do not exceed the maximum of 3.3V, to avoid damaging the device.

I did not dive to much in the attenuation area so I don't know if it can measure 0-3.3V then or it is only save to feed 3.3 V but you can measure still 0-1.1V only.

**Comment by amotl** [comment]
Thanks @ClemensGruber.

So, we might think about using `ADC.ATTN_11DB` when sampling the ADC?

https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/master/terkin/sensor/system.py#L99-L110

**Comment by ayoy** [comment]
Hello and sorry for the late response.

Just wanted to point out that my code is adjusted to my custom board, where I use 100kΩ / 47 kΩ voltage divider, which gives ~1342mV for 4.2V battery voltage. I'm using 2.5dB attenuation that allows for measuring up to 1382mV.

So the attenuation is effectively enhancing your valid measurement range. With attenuation of 11dB you can measure up to 3.3V, i.e. the 3300mV would be recognized as 4095 by the ADC. If you use 115 kΩ / 56 kΩ divider and get 1.637V out of 5V, you should be good with 6dB attenuation (although I don't recall the exact range of measurement for that attenuation value, but my code would log it to the console).

Based on my code:
https://github.com/ayoy/upython-aq-monitor/blob/lora/lib/adc.py
you should only change:
* `attn` parameter in line 6,
* numbers at the end of line 25, where the numerator is the sum of resistor values and denominator is the R2 (the resistor between the input pin and the ground).

I hope that it clears things up a bit :)

PS. I once applied a full 4.2V to the ADC input because of a bug in my prototype PCB, and my LoPy handled that gracefully (i.e. it didn't burn) :) your mileage may vary though so be careful!

**Comment by amotl** [comment]
Dear @ayoy,

thank you so much for your quick response. We changed the voltage divider parameters appropriately based on the information you provided with 73d8d688. Now, the battery level / vcc gets measured at around 3.92V instead of 4.32V when running attached to an USB charger, while the LiPo connected during charging delivers a voltage of 3.7 V as printed on it. This reading feels more reasonable.

With kind regards,
Andreas.

**Comment by amotl** [comment]
As we believe the implementation of the Vcc sensor is sound now (thanks again, @ayoy), we want to dedicate some minutes to the temperature sensor readings coming from the Pycom module available through `machine.temperature()`.

There's also a formula involved for computing the effective temperature in °C from the corresponding value, so we are humbly asking the community for reviewing the current implementation [1].

Thanks already!

[1] https://github.com/hiveeyes/hiveeyes-micropython-firmware/blob/3844b93e6c088703b9b446e2ce136ff244b8bff4/terkin/sensor/system.py#L27-L53

**Comment by amotl** [comment]
Re. Vcc sensor: @ClemensGruber just told me that the board he designed for the Bee Observer project has different resistors again. So, we should adapt the values appropriately and at least put some guidelines into the example configuration settings for new users to recognize.

**Comment by ClemensGruber** [comment]
Many thanks @ayoy, so you are using with a 100kΩ / 47 kΩ voltage divider this code
> vbatt = (apin.value_to_voltage(int(meanADC)))*147/47

The first value is the sum of the two resistors! 

With our hardware -- 10 MΩ / 2 MΩ -- I think we have to use 

# Sum of resistor values.
'resistor_sum': 12,
# Resistor between input pin and ground.
'resistor_pin': 2,

In case we use the expansion board in addition to our PCB we have to disable the expansion board's voltage divider becaus we are using the same pin for battery monitoring!

**Comment by amotl** [comment]
@ClemensGruber: I will rename the configuration settings to `resistor_r1` and `resistor_r2` and do the computation internally in order to minimize confusion about summing or not.

**Comment by amotl** [comment]
We have been able to dedicate some time to this topic [1] (thanks, everyone!) and want to share the outcome of our research.

- Pycom Expansion board v3.0: 115 kΩ / 56 kΩ
- Pycom Expansion board v3.1: 1 MΩ / 1 MΩ
- Pycom Expansion board v3.2: 1 MΩ / 1 MΩ
- BOB-HAT-V5: 1 MΩ / 470 kΩ or 220 kΩ
- BOB-SHIELD: 10 MΩ / 2 MΩ
- Air Quality monitor: 100kΩ / 47 kΩ, measured with 2.5dB attenuation

(all readings using 6dB attenuation unless otherwise noted)

[1] https://community.hiveeyes.org/t/batterieuberwachung-voltage-divider-und-attenuation-fur-microypthon-firmware/2128

**Comment by amotl** [comment]
Closing this for now. Please feel free to reopen.
