### ISSUE TITLE
Can not justify scale with 'scale' and 'offset' parameter

### ISSUE THREAD

**Issue by ClemensGruber** [hiveeyes/hiveeyes-micropython-firmware#6]
I have tried to modify `scale` and `offset` in the settings.py 

    'hx711': {
        'pin_dout': 'P22',
        'pin_pdsck': 'P21',
        'scale':  50000000.0,
        'offset': 10000000.0,
    },

but it seems that this has no effect on the measured "weight" value, see  https://community.hiveeyes.org/t/justify-scale-for-the-micropython-firmware/2104

**Comment by amotl** [comment]
Thanks Clemens. We will have a look into this.

**Comment by amotl** [comment]
We have closed this issue by commit and can confirm it also works for us. Please reopen if needed.
