### ISSUE TITLE
Improve error signalling for missing "topology" configuration setting

### ISSUE THREAD

**Issue by ClemensGruber** [hiveeyes/hiveeyes-micropython-firmware#7]
for the new software version you need an additional 
'topology': 'mqttkit',

in the settings files for the hiveeyes telemetry

**Comment by amotl** [comment]
That's true. Thanks for notifying us about it.

**Comment by amotl** [comment]
We have a question about this yet: Have you been able to deduce the reason from the error message somehow?

**Comment by ClemensGruber** [comment]
Not the exact reasion, I got only 

29.6488 [terkin.datalogger        ] WARNING: Telemetry status: FAILURE. 1 out of 2 targets failed. Status: {'https://bee-observer.org/api/sensors': True, 'mqtt://swarm.hiveeyes.org': False}
26.7088 [terkin.telemetry ] ERROR : MQTT publishing failed

see also https://community.hiveeyes.org/t/kontinuierliches-bugfixing-des-hiveeyes-micropython-datenloggers/2121/20 and ff

**Comment by amotl** [comment]
Now, the log output got improved to indicate something is wrong with the configuration.
```
[terkin.telemetry] ERROR  : Telemetry to mqtt://daq.example.org/ failed
Traceback (most recent call last):
  File "/flash/lib/terkin/telemetry.py", line 117, in transmit
  File "/flash/lib/terkin/telemetry.py", line 272, in transmit
  File "/flash/lib/terkin/telemetry.py", line 420, in send
TelemetryTransportError: Empty MQTT topic, please configure MQTT URI with path component or topology with address
```
